// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bios: dynamic(() => import("./Bios")),
  call_to_action: dynamic(() => import("./CallToAction")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  map: dynamic(() => import("./Map")),
  restaurant_list: dynamic(() => import("./RestaurantList")),
};
